swagger: "2.0"
info:
  title: Hanet Webhook API
  description: API nhận webhook từ Hanet
  version: "1.0.0"

basePath: "/"
schemes:
  - "http"

paths:
  /hanet-webhook:
    post:
      tags:
        - Webhook
      summary: Nhận dữ liệu webhook từ Hanet
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      parameters:
        - in: body
          name: payload
          description: Webhook payload
          required: false
          schema:
            type: object
      responses:
        200:
          description: Webhook received successfully
          schema:
            type: object
            properties:
              status:
                type: string
                example: ok
